# Schema for the views plugins of the REST module.

views.display.rest_export:
  type: views_display_path
  label: 'REST display options'
  mapping:
    auth:
      type: sequence
      label: 'Authentication'
      sequence:
        type: string
        label: 'Authentication Provider'

views.row.data_hydroid:
  type: views_row
  label: 'Field row'
  mapping:
    hydroid_options:
      type: sequence
      label: 'Options'
      sequence:
        alias:
          type: string
          label: 'Alias for ID'
        raw_output:
          type: boolean
          label: 'Raw output for ID'

views.style.serializer:
  type: views_style
  label: 'Serialized output format'
  mapping:
    formats:
      type: sequence
      label: 'Formats'
      sequence:
        type: string
        label: 'Format
