# Schema for the views plugins of the REST module.

views.row.data_hydroid:
  type: views_row
  label: 'Field row'
  mapping:
    rootType:
      type: sequence
      label: 'Content type to treat as root'

